### ISSUE TITLE
Lolicon does not restart.

### ISSUE THREAD

**Issue by dkrmdi** [cuevavirus/LOLIconFastSwitch#1]
I can turn off lolicon, but I cannot turn it back on using this app.
I'm still glad I don't have to add haltpoint(#) in my config.txt and reboot everytime I wanted to run Adrenaline.

I am on 3.60 enso. I can show you my config.txt if you need. I hope a fixed version gets released.

**Comment by cuevavirus** [comment]
Please post your config

**Comment by dkrmdi** [comment]
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from molecularShell for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
# henkaku.skprx is hard-coded to load and is not listed here
ur0:tai/plugins/nonpdrm.skprx
ur0:tai/plugins/kuio.skprx
ur0:tai/plugins/reF00D.skprx
ur0:tai/plugins/repatch.skprx
ur0:tai/plugins/ioplus.skprx
ur0:tai/plugins/storagemgr.skprx
ur0:tai/plugins/lolicon.skprx
*main
# main is a special titleid for SceShell
ur0:tai/plugins/pngshot.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*PCSC00045
ur0:tai/plugins/kzv.suprx
*PCSG00947
ur0:tai/plugins/VGi.suprx
*PCSG01102
ur0:tai/plugins/VGi.suprx
*PCSH00057
ur0:tai/plugins/VGi.suprx
*PCSE01268
ur0:tai/plugins/VGi.suprx
*ALL
ur0:tai/plugins/vitagrafix.suprx
ur0:tai/plugins/forcelang.suprx
ur0:tai/plugins/remaPSV.suprx
x
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*PCSC00045
ur0:tai/plugins/kzv.suprx
*PCSG00947
ur0:tai/plugins/VGi.suprx
*PCSG01102
ur0:tai/plugins/VGi.suprx
*PCSH00057
ur0:tai/plugins/VGi.suprx
*PCSE01268
ur0:tai/plugins/VGi.suprx
*ALL
ur0:tai/plugins/forcelang.suprx
ur0:tai/plugins/dsmotion.suprx
ur0:tai/plugins/InfiniteNet.suprx
ur0:tai/plugins/itls.suprx
ur0:tai/plugins/remaPSV.suprx
ur0:tai/plugins/vitagrafix.suprx


That was a very quick reply. Thank you.

**Comment by dkrmdi** [comment]
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from molecularShell for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
# henkaku.skprx is hard-coded to load and is not listed here
ur0:tai/plugins/storagemgr.skprx
ur0:tai/plugins/udcd_uvc_oled_off.skprx
ur0:tai/plugins/ds4vita.skprx
ur0:tai/plugins/dsmotion.skprx
ur0:tai/plugins/lolicon.skprx
ur0:tai/plugins/nonpdrm.skprx
ur0:tai/plugins/kuio.skprx
ur0:tai/plugins/reF00D.skprx
ur0:tai/plugins/repatch.skprx
ur0:tai/plugins/ioplus.skprx
ur0:tai/plugins/music_premium.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
*main
# main is a special titleid for SceShell
ur0:tai/plugins/download_enabler.suprx
ur0:tai/plugins/pngshot.suprx
ur0:tai/plugins/shellbat.suprx
ur0:tai/plugins/quick_power.suprx
ur0:tai/plugins/quick_volume.suprx
ur0:tai/plugins/TrImpose.suprx
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*PCSC00045
ur0:tai/plugins/kzv.suprx
*PCSG00947
ur0:tai/plugins/VGi.suprx
*PCSG01102
ur0:tai/plugins/VGi.suprx
*PCSH00057
ur0:tai/plugins/VGi.suprx
*PCSE01268
ur0:tai/plugins/VGi.suprx
*ALL
ur0:tai/plugins/forcelang.suprx
ur0:tai/plugins/dsmotion.suprx
ur0:tai/plugins/InfiniteNet.suprx
ur0:tai/plugins/itls.suprx
ur0:tai/plugins/remaPSV.suprx
ur0:tai/plugins/vitagrafix.suprx

**Comment by dkrmdi** [comment]
I'm sorry. I had posted the wrong config.txt.

**Comment by cuevavirus** [comment]
It's because you have lolicon at `ur0:tai/plugins/lolicon.skprx` but loliconfastswitch loads lolicon only from `ur0:tai/lolicon.skprx`. So if you just move lolicon there and update the config it'll work as expected.

**Comment by dkrmdi** [comment]
I moved lolicon and it works! Thank you so much.
